app = 'pdftoimage'
primary_region = 'bom'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ['app']

  [[http_service.concurrency]]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 4096
