# fly.toml app configuration file generated for pdftoimage on 2025-07-28T04:29:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdftoimage'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
  processes = ['app']

  # Auto-scaling based on concurrent requests
  [[http_service.concurrency]]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  # Auto-scaling based on machine load
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  memory = '6gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 6144
