# fly.toml app configuration file generated for pdf-to-image-ycp4cg on 2025-09-06T10:29:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdf-to-image-ycp4cg'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
