services:
  - type: web
    name: pdf-to-image-converter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # 1 vCPU, 2GB RAM
    region: oregon
    branch: main
    buildCommand: echo "Using Docker build"
    startCommand: echo "Using Docker start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: GCS_PROJECT_ID
        value: tokyo-portal-459007-n8
      - key: GCS_BUCKET_NAME
        value: gradonix
      - key: GCS_SERVICE_ACCOUNT_KEY
        sync: false # Set this in the Render dashboard as a secret
    # No disk needed since we're using GCS
    healthCheckPath: /health
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 5
      targetCPUPercent: 90
      targetMemoryPercent: 90
    autoDeploy: true
